apiVersion: v1
kind: Service
metadata:
  name: deployment-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
  selector:
    app: deployment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
spec:
  selector:
    matchLabels:
      app: deployment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: deployment-service
    spec:
      containers:
        - name: instance-service
          image: 192.168.1.104:5000/deployment-service:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 2000Mi
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 160
            periodSeconds: 10
            timeoutSeconds: 5